spring:
  application:
    name: consumer
  main:
    # Spring Boot 2.1 需要设定
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        namespace: 9466c0d9-b5bd-4f1a-9936-10e37656afdf
        cluster-name: BJ
        metadata:
          version: v1
          target-version: v1
#  datasource:
#      driver-class-name: com.mysql.jdbc.Driver
#      username: ${MYSQL_USER:root}
#      password: ${MYSQL_PASSWORD:root}
#      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/easy_jdbc?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
easyjdbc:
#  dialect : mysql
#  basePackage: com.xphsc.*
  enabled: false

dubbo:
  scan:
    # dubbo 服务扫描基准包
    base-packages: com.xphsc.dubbo
  protocol:
    # dubbo 协议
    name: dubbo
    # dubbo 协议端口（ -1 表示自增端口，从 20880 开始）
    port: -1
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
server:
  port: 2004
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  level:
    com.xphsc: debug
