server:
  port: 18086
spring:
  application:
    name: service-gateway-provider
  cloud:
   nacos:
     discovery:
      server-addr: 127.0.0.1:8848
   gateway:
     routes[0]:
        id: nacos-route
        uri: lb://service-gateway-provider
        predicates[0]:
          name: Path
          args[pattern]: /nacos/**
        filters[0]: StripPrefix=1
management:
   endpoints:
   web:
   exposure:
    include: *