server:
  port: 18085
spring:
  application:
    name: service-gateway-provider
  cloud:
   nacos:
     discovery:
      server-addr: 127.0.0.1:8848
management:
   endpoints:
   web:
   exposure:
    include: *